### ISSUE TITLE
Unhandled rejection Error: Error promptTimeslotSelection:

### ISSUE THREAD

**Issue by languantan** [GovTechSG/butler-bot#4]
device log:
```
Unhandled rejection Error: Error promptTimeslotSelection: {}
    at /home/ubuntu/butler-bot/build/modules/TelegramBot.js:387:11
0|build    |     at tryCatcher (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/util.js:16:23)
0|build    |     at Promise._settlePromiseFromHandler (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/promise.js:510:31)
0|build    |     at Promise._settlePromise (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/promise.js:567:18)
0|build    |     at Promise._settlePromise0 (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/promise.js:612:10)
0|build    |     at Promise._settlePromises (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/promise.js:687:18)
0|build    |     at Async._drainQueue (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/async.js:133:16)
0|build    |     at Async._drainQueues (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/async.js:143:10)
0|build    |     at Immediate.Async.drainQueues (/home/ubuntu/butler-bot/node_modules/bluebird/js/release/async.js:17:14)
0|build    |     at runCallback (timers.js:651:20)
0|build    |     at tryOnImmediate (timers.js:624:5)
0|build    |     at processImmediate [as _immediateCallback] (timers.js:596:5)
```

## Repro
1. /book
1. Any room
1. Select date
1. Select time
1. Press Back
1. Error pops up

**Comment by languantan** [comment]
Closing as it's just a warning and doesn't crash the bot
